name: CI/CD workflow

on: workflow_dispatch

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: mlops/lab11
  S3_BUCKET: mlops-lab11-dw

jobs:
  integration:
    name: checks_and_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        # This step checks out your repository code so the workflow can access it
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        # TODO: Add command to sync ONLY integration group dependencies
        run: uv sync --group integration
     
      # TODO: Add steps for 'ruff check' and 'pytest'

      - name: run pre-commit
        run: uv run pre-commit run --all-files

      - name: run ruff check
        run: uv run ruff check .

      - name: run pytest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        run: |
          uv run python src/lab11_lib/scripts/download_artifacts.py  
          uv run -m pytest 

      